---
name: "Continuous Deployment"

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_repository_name
        run: echo ::set-output name=REPO_NAME::${{ github.event.repository.name }}
        shell: bash
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: install yarn
        run: npm install -g yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install dependancy
        run: |
          yarn install
      - name: export web
        run: |
          rm -rf public/
          yarn build
          mv dist/ front/
      - name: compress things up
        run: |
          tar -cvf ${{ steps.get_repository_name.outputs.REPO_NAME }}-static.tar.gz front/
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            ${{ steps.get_repository_name.outputs.REPO_NAME }}-static.tar.gz
