---
name: "Continuous Integration"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_repository_name
        run: echo ::set-output name=REPO_NAME::${{ github.event.repository.name }}
        shell: bash
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: install yarn
        run: npm install -g yarn
      - name: install dependancy
        run: |
          yarn install
      - name: export web
        run: |
          rm public/*.csv
          yarn export
          mv out/ front/
      - name: compress things up
        run: |
          tar -cvf ${{ steps.get_repository_name.outputs.REPO_NAME }}-static.tar.gz front/
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ${{ steps.get_repository_name.outputs.REPO_NAME }}-static.tar.gz
